/**
 * Where the printed card and the SRD disagree, and which one we ship.
 *
 * The System Reference Document 2.0 (25 August 2026) reprints the corebook's
 * domain deck, and four of the 189 cards do not read the way the Card Creator
 * still prints them. That is a fourth kind of file in this folder and it needs
 * saying why, because there are three obvious places to make a change like this
 * and all three are wrong.
 *
 * **Not `domain-cards.mjs`.** It is generated by `tools/fetch-cards.mjs` from
 * the committed snapshot, so a hand-edit there survives exactly until somebody
 * re-fetches — and survives *silently* until then, which is worse: the file
 * looks like every other line in it, and nothing on the page says a human wrote
 * that sentence.
 *
 * **Not `official-cards.json`.** The snapshot is a record of what upstream said
 * on the day it was taken. Editing it makes the record a fiction and takes
 * `tools/check-cards.mjs`'s whole audit with it — that tool compares the packs
 * against the snapshot, and a snapshot we have been correcting is a mirror.
 *
 * **Not `TYPOS` in `tools/fetch-cards.mjs`.** That table is the right *shape*
 * and the wrong claim. Every entry in it is upstream having made a mistake in
 * transmission — a doubled article, an undecoded entity, a sentence with no full
 * stop — and none of them changes what a card does. These four do. "Take half
 * damage" is a rule, not a typo, and filing it beside "create a a wall" would
 * say that Darrington Press mistyped their own errata.
 *
 * So it is an **overlay**, in exactly the idiom `withDice` and `withDamage`
 * already use: a hand-authored table keyed `type:name`, applied downstream at
 * `domains.mjs`'s own `export default`, where a re-fetch cannot reach it. The
 * generated module stays a faithful transcription of the snapshot, the snapshot
 * stays a record, and the correction is one file that says out loud that it is
 * one.
 *
 * ── the discipline ────────────────────────────────────────────────────
 * Every patch records **both** texts. `find` is the sentence as the generated
 * corpus prints it today and `to` is the SRD's, matched literally and exactly
 * once, and a `find` that stops matching **throws** rather than being skipped.
 * That is `TYPOS`'s own rule and it is here for `TYPOS`'s own reason: upstream
 * having adopted the erratum and upstream having rewritten the card around it
 * look identical from here, and only one of them is fine. The failure is loud
 * because the quiet version — an overlay that shrugs and applies nothing — ships
 * a card that reads as though nobody had ever looked at it.
 *
 * It is applied to the **source card** rather than to the built document,
 * unlike its two siblings, and that is a consequence of what an erratum is. A
 * counter and a damage expression are annotations *about* a card and belong on
 * the document; this is the card's own text, and the card's own text is markdown
 * until `domainCardItem` renders it. Writing `find` against the rendered HTML
 * would couple every patch to the markdown renderer — Unleash Chaos's price is
 * `**Mark Stress**` on the card and `<strong>Mark Stress</strong>` afterwards —
 * so the overlay runs one step earlier, where the sentence is still the sentence.
 *
 * ── what is deliberately not here ─────────────────────────────────────
 * **Notorious** (Grace, level 10). The SRD's appendix prints the card without
 * its last sentence — "This card doesn't count against your loadout's domain
 * card maximum of 5 and can't be placed in your vault." — and that sentence
 * stays. The Card Creator still prints it, it is the whole reason the card is
 * worth a level 10 slot, and an *omission in an appendix* is not an erratum:
 * the four below are each a word or a clause somebody deliberately changed,
 * while this is a line that is either there or it is not, in a document that is
 * a reprint rather than a printing. Two sources disagreeing about whether a
 * sentence exists is a reason to keep the one that has it. Recorded here so the
 * next reader who diffs the SRD against this pack does not have to re-decide it.
 */

/**
 * One correction, keyed by the document the card becomes.
 *
 * `why` is the SRD's change stated as a rules difference rather than as a diff,
 * because "temporary" is one word and what it does is put a duration on a wall
 * that used to have none.
 */
const ERRATA = {
  /* The card said what happens to the *first* adversary and left the others to
     the table. Every other card in the corpus that hits several targets says
     what each of them takes, and this one now does too. */
  "domainCard:Whirlwind": [
    {
      find:
        "you can **spend a Hope** to use the attack against all other targets " +
        "within Very Close range.",
      to:
        "you can **spend a Hope** to use the attack against all other targets " +
        "within Very Close range. All additional adversaries you succeed against " +
        "with this ability take half damage.",
      why:
        "SRD 2.0 adds the half-damage clause. Without it a level 1 card dealt a " +
        "full weapon's damage to every adversary in Very Close range.",
    },
  ],

  /* An amount, on the one card in the deck whose price had none. The sheet
     reads a price out of a card's own prose (`priceOf` in `sheets/cards.ts`),
     and that pattern requires the number — so before this the card charged
     nothing at all, which is the shape of gap `tools/check-cards.mjs`'s price
     ratchet exists to surface. It has an entry there now. */
  "domainCard:Unleash Chaos": [
    {
      find: "**Mark Stress** to replenish this card with tokens (up to your Spellcast trait).",
      to: "**Mark a Stress** to replenish this card with tokens (up to your Spellcast trait).",
      why:
        "SRD 2.0 prints the amount. “Mark Stress” names no quantity, which is a " +
        "sentence no other card in the corpus writes.",
    },
  ],

  /* Reveal read as though a clause had been pasted in and its neighbour not
     taken out — the roll it names is the Spellcast Roll in the sentence before,
     and there is no Difficulty for anything to succeed *against*. The SRD drops
     it and the sentence closes. */
  "domainCard:Book of Vagras": [
    {
      find:
        "If there is anything magically hidden within Close range, the roll " +
        "would succeed against, it is revealed.",
      to: "If there is anything magically hidden within Close range, it is revealed.",
      why:
        "SRD 2.0 drops a garbled clause from the Reveal spell. It named no " +
        "Difficulty and left the sentence without a subject.",
    },
  ],

  /* One word, and it is the whole duration. Wall of Flame's neighbour on the
     same grimoire — Time Lock — says "until your next rest" out loud; this said
     nothing, so the wall stood for the rest of the campaign. */
  "domainCard:Book of Grynn": [
    {
      find: "On a success, create a wall of magical flame between two points within Far range.",
      to:
        "On a success, create a temporary wall of magical flame between two " +
        "points within Far range.",
      why:
        "SRD 2.0 adds “temporary” to Wall of Flame, which is the rules' own " +
        "keyword for a state that ends when the fiction says so.",
    },
  ],
};

export default ERRATA;

/**
 * Apply the corrections to a deck's source cards.
 *
 * Called at `domains.mjs`'s own `export default`, beside `withDice` and
 * `withDamage` and for the same reason: `tools/verify/` imports these modules
 * directly to draw THE DECK, and a correction applied centrally in
 * `build-packs.mjs` would be a correction that page never sees.
 *
 * Cards are **copied** rather than patched in place. `domain-cards.mjs` is a
 * module and its array is shared with every other importer — `tools/check-marked.mjs`
 * reads it to measure the printed corpus's damage bands — and an overlay that
 * mutated it would be editing the generated file after all, just at run time.
 *
 * `type` is the subtype these entries become rather than one they carry: a
 * source card is a name, a level and a paragraph, and `domainCardItem` is what
 * makes it a document. It is a parameter rather than a constant so the key stays
 * the `type:name` its three sibling files use — a reader holding all four is
 * holding one index, not four.
 */
export function withErrata(cards, type = "domainCard") {
  const used = new Set();
  const out = cards.map((c) => {
    const key = `${type}:${c.name}`;
    const patches = ERRATA[key];
    if (!patches) return c;
    used.add(key);
    let text = String(c.text);
    for (const p of patches) {
      if (!text.includes(p.find)) {
        throw new Error(
          `card-errata: ${key} no longer says “${p.find}”. The generated corpus has ` +
            `changed under this overlay — re-read the erratum against the card's ` +
            `current text before deciding whether it still applies.`,
        );
      }
      text = text.replace(p.find, p.to);
    }
    return { ...c, text };
  });

  for (const key of Object.keys(ERRATA)) {
    if (!used.has(key)) {
      throw new Error(
        `card-errata: ${key} names a card that is not in this deck. A renamed or ` +
          `withdrawn card is an erratum nobody can apply, so it fails here rather ` +
          `than being silently dropped.`,
      );
    }
  }

  return out;
}
